button_card_templates: !include button_card_templates.yaml

views:
  - type: custom:grid-layout
    path: 0
    layout:
      #default
      grid-gap: var(--custom-layout-card-padding)
      grid-template-columns: repeat(4, 1fr) 0
      grid-template-rows: 0 repeat(2, fit-content(100%)) 0fr
      grid-template-areas: |
        "sidebar  .           .       .       ."
        "sidebar  vardagsrum  studio  sovrum  ."
        "sidebar  media       övrigt  hemma   ."
        "sidebar  footer      footer  footer  ."
      mediaquery:
        #phone
        "(max-width: 800px)":
          grid-gap: calc(var(--custom-layout-card-padding) * 1.5)
          grid-template-columns: 0 repeat(2, 1fr) 0
          grid-template-rows: 0 repeat(5, fit-content(100%)) 0fr
          grid-template-areas: |
            ".  .           .        ."
            ".  sidebar     sidebar  ."
            ".  vardagsrum  sovrum   ."
            ".  studio      övrigt   ."
            ".  media       hemma    ."
            ".  footer      footer   ."
            ".  .           .        ."
        #portrait
        "(max-width: 1200px)":
          grid-gap: var(--custom-layout-card-padding)
          grid-template-columns: repeat(3, 1fr) 0
          grid-template-rows: 0 repeat(3, fit-content(100%)) 0fr
          grid-template-areas: |
            "sidebar  .           .       ."
            "sidebar  vardagsrum  sovrum  ."
            "sidebar  studio      övrigt  ."
            "sidebar  media       hemma   ."
            "sidebar  footer      footer  ."
            "sidebar  .           .       ."
    cards:

      - type: custom:button-card #extra_styles fix

      #################################################
      #                                               #
      #                    SIDEBAR                    #
      #                                               #
      #################################################

      - type: vertical-stack
        view_layout:
          grid-area: sidebar
        cards:
          - type: custom:button-card
            entity: sensor.template_sidebar
            template: sidebar_template

          - type: conditional
            conditions:
              - entity: input_boolean.laundry_display
                state: 'on'
            card:
              type: custom:button-card
              entity: timer.laundry
              template: laundry

          - type: grid
            cards:
              - type: button
                icon: custom:roborock-vacuum
                tap_action:
                  !include popup/sidebar_vacuum.yaml
                hold_action:
                  action: none

              - type: button
                icon: mdi:information-outline
                tap_action:
                  !include popup/sidebar_information.yaml
                hold_action:
                  action: none

              - type: button
                icon: mdi:arrow-up-bold-circle-outline
                tap_action:
                  !include popup/sidebar_update.yaml
                hold_action:
                  action: none

      #################################################
      #                                               #
      #                  VARDAGSRUM                   #
      #                                               #
      #################################################

      - type: grid
        title: Vardagsrum
        view_layout:
          grid-area: vardagsrum
        columns: 2
        cards:

          - type: custom:button-card
            entity: light.vardagsrum_group #hue_group
            name: Belysning
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: light.horna
            name: Hörnlampa
            template:
              - light
              - icon_shade

          - type: custom:button-card
            entity: media_player.sony_bravia_tv
            name: Tv
            hold_action:
              !include popup/vardagsrum_tv.yaml
            template:
              - base
              - icon_tv
              - loader

          - type: custom:button-card
            entity: switch.deltaco_sh_p01
            name: Balkong
            hold_action:
              !include popup/vardagsrum_balkong.yaml
            template:
              - base
              - icon_hue
              - loader

      #################################################
      #                                               #
      #                    STUDIO                     #
      #                                               #
      #################################################

      - type: grid
        title: Studio
        view_layout:
          grid-area: studio
        columns: 2
        cards:

          - type: custom:button-card
            entity: light.dator
            name: Datorlampa
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: light.taklampor #hue_group
            name: Taklampor
            template:
              - light
              - icon_spot

          - type: custom:button-card
            entity: switch.computer_imac
            name: Dator
            triggers_update:
              - lock.dator
              - script.home_leave
            hold_action:
              !include popup/studio_dator.yaml
            template:
              - base
              - icon_imac
              - loader
              - lock

          - type: custom:button-card
            entity: switch.wemo_monitors
            name: Monitorer
            triggers_update: sensor.monitors_volume
            hold_action:
              !include popup/studio_monitorer.yaml
            template:
              - base
              - icon_monitors
              - circle
              - loader
            variables:
              circle_input: >
                [[[
                  var entity_id = 'sensor.monitors_volume';
                  return states[entity_id] === undefined ? null : states[entity_id].state;
                ]]]

      #################################################
      #                                               #
      #                    SOVRUM                     #
      #                                               #
      #################################################

      - type: grid
        title: Sovrum
        view_layout:
          grid-area: sovrum
        columns: 2
        cards:

          - type: custom:button-card
            entity: light.sovrum #hue_group
            name: Sänglampor
            template:
              - light
              - icon_lamp

          - type: custom:button-card
            entity: climate.luftkylare
            name: Klimat
            hold_action:
              !include popup/sovrum_klimat.yaml
            template:
              - base
              - icon_climate
              - climate
              - loader
            variables:
              circle_input: >
                [[[
                  if (entity) {
                    return entity.state == 'on' ?
                      entity.attributes.temperature :
                      entity.attributes.current_temperature;
                  }
                ]]]

          - type: custom:button-card
            entity: switch.playstation_5
            name: Playstation
            hold_action:
              !include popup/vardagsrum_playstation.yaml
            template:
              - base
              - icon_ps5
              - loader

          - type: custom:button-card
            entity: media_player.samsung_tv
            name: "Tv\u00B2"
            hold_action:
              !include popup/sovrum_tv2.yaml
            template:
              - base
              - icon_tv
              - loader

      #################################################
      #                                               #
      #                     MEDIA                     #
      #                                               #
      #################################################

      - type: grid
        title: Media
        view_layout:
          grid-area: media
        columns: 1
        cards:

          - type: custom:swipe-card
            start_card: 1
            parameters:
              roundLengths: true
              effect: coverflow
              speed: 650
              spaceBetween: 20
              threshold: 7
              coverflowEffect:
                rotate: 80
                depth: 300
            cards:

              - type: horizontal-stack
                cards:

                  - type: conditional
                    conditions:
                      - entity: input_select.conditional_media
                        state: Senast nedladdat
                    card:
                      type: custom:button-card
                      entity: sensor.plex_recently_added
                      tap_action:
                        action: none
                      template:
                        - conditional_media
                        - recently_downloaded
                        - icon_plex

                  - type: conditional
                    conditions:
                      - entity: input_select.conditional_media
                        state: Vardagsrum
                    card:
                      type: custom:button-card
                      entity: media_player.vardagsrum
                      template:
                        - conditional_media
                        - icon_apple_tv

                  - type: conditional
                    conditions:
                      - entity: input_select.conditional_media
                        state: Sovrum
                    card:
                      type: custom:button-card
                      entity: media_player.sovrum
                      template:
                        - conditional_media
                        - icon_apple_tv

                  - type: conditional
                    conditions:
                      - entity: input_select.conditional_media
                        state: Spotify
                    card:
                      type: custom:button-card
                      entity: media_player.spotify
                      template:
                        - conditional_media
                        - icon_spotify

                  - type: conditional
                    conditions:
                      - entity: input_select.conditional_media
                        state: Google Nest Mini
                    card:
                      type: custom:button-card
                      entity: media_player.kok
                      template:
                        - conditional_media
                        - icon_nest_mini

              - type: grid
                columns: 2
                cards:

                  - type: custom:button-card
                    entity: media_player.vardagsrum
                    name: Vardagsrum
                    template:
                      - media
                      - icon_apple_tv

                  - type: custom:button-card
                    name: Sovrum
                    entity: media_player.sovrum
                    template:
                      - media
                      - icon_apple_tv

                  - type: custom:button-card
                    entity: media_player.spotify
                    name: Spotify
                    template:
                      - media
                      - icon_spotify

                  - type: custom:button-card
                    entity: media_player.kok
                    name: Nest Mini
                    template:
                      - media
                      - icon_nest_mini

      #################################################
      #                                               #
      #                    ÖVRIGT                     #
      #                                               #
      #################################################

      - type: grid
        title: Övrigt
        view_layout:
          grid-area: övrigt
        columns: 2
        cards:

          - type: custom:button-card
            entity: light.badrum #hue_group
            name: Badrum
            template:
              - light
              - icon_bathroom

          - type: custom:button-card
            entity: fan.studio_wemo
            name: "Fläkt\u00B2"
            hold_action:
              !include popup/studio_flakt.yaml
            template:
              - base
              - icon_fan2
              - loader

          - type: custom:button-card
            entity: light.garderob
            name: Garderob
            template:
              - light
              - icon_closet

          - type: custom:button-card
            entity: light.hall #hue_group
            name: Hall
            template:
              - light
              - icon_spot

      #################################################
      #                                               #
      #                     HEMMA                     #
      #                                               #
      #################################################

      - type: grid
        title: Hemma
        view_layout:
          grid-area: hemma
        columns: 2
        cards:

          - type: custom:button-card
            entity: person.matte
            name: Mattias
            tap_action:
              !include popup/hemma_mattias.yaml
            hold_action:
              action: none
            template: person

          - type: custom:button-card
            entity: person.sanja
            name: Sanja
            tap_action:
              !include popup/hemma_sanja.yaml
            hold_action:
              action: none
            template: person

          - type: custom:button-card
            entity: script.home_leave
            name: Stäng allt
            hold_action:
              action: none
            template:
              - base
              - icon_away

          - type: custom:button-card
            entity: script.home_arrive
            name: Hemma
            hold_action:
              action: none
            template:
              - base
              - icon_home

      #################################################
      #                                               #
      #                    FOOTER                     #
      #                                               #
      #################################################

      - type: custom:button-card
        view_layout:
          grid-area: footer
        entity: sensor.covid_19_folkhalsomyndigheten
        template: coronavirus
