homeassistant:
  customize:

    ####################################################
    #                                                  #
    #                    CUSTOMIZE                     #
    #                                                  #
    ####################################################

    #light
    light.vardagsrum_group:
      friendly_name: Belysning
      icon: mdi:lamp
    light.dator:
      friendly_name: Datorlampa
    light.sovrum:
      friendly_name: Sänglampor
      icon: mdi:floor-lamp

    #esphome
    sensor.gosund_1_daily_energy:
      friendly_name: gosund_1_da
    sensor.gosund_2_daily_energy:
      friendly_name: Electrolux ChillFlex Pro Gold
    sensor.gosund_3_daily_energy:
      friendly_name: gosund_3_da

    #media_player
    media_player.sony_bravia_tv:
      friendly_name: Tv
      device_class: tv
      source_list: ['HDMI 1', 'HDMI 2/MHL', 'HDMI 3', 'HDMI 4']
    media_player.samsung_tv:
      friendly_name: "Tv\u00B2"
      device_class: tv
      source_list: ['TV', 'HDMI']
    media_player.spotify:
      friendly_name: Spotify
    media_player.kok:
      friendly_name: Google Nest Mini

    #binary_sensor
    binary_sensor.sensor_hall_motion:
      friendly_name: hallen
    binary_sensor.sensor_badrum_motion:
      friendly_name: badrummet
    binary_sensor.sensor_garderob_motion:
      friendly_name: klädkammaren
    binary_sensor.wemo_motion:
      friendly_name: vardagsrummet

    #battery
    sensor.switchbot_battery:
      friendly_name: Switchbot
      device_class: battery
    sensor.dimmer_badrum_battery_level:
      friendly_name: Dimmer Badrum
    sensor.dimmer_sovrum_battery_level:
      friendly_name: Dimmer Sovrum
    sensor.template_hue_motion_battery_badrum:
      friendly_name: Sensor Badrum
    sensor.template_hue_motion_battery_garderob:
      friendly_name: Sensor Garderob
    sensor.template_hue_motion_battery_hall:
      friendly_name: Sensor Hall

    #fan
    fan.studio_wemo:
      icon: custom:pedestal-fan
    fan.sovrum_anslut:
      icon: custom:pedestal-fan

    # template
    sensor.template_coronavirus:
      friendly_name: Coronavirus
    sensor.template_dockermon_mem:
      friendly_name: Minne
    sensor.template_imac_vpn:
      friendly_name: VPN
    sensor.template_printer_status:
      friendly_name: Skrivare
    sensor.template_fullykiosk_storage:
      friendly_name: Lagring
    sensor.template_fullykiosk_memory:
      friendly_name: Minne
    sensor.template_fullykiosk_last_app_start:
      friendly_name: Senast omstart
    sensor.template_nas_status:
      friendly_name: Systemhälsa
    sensor.template_nas_vpn:
      friendly_name: VPN

    #sidebar_vacuum.yaml
    vacuum.valetudo_robot:
      friendly_name: Roborock S5
      icon: custom:roborock-vacuum
    sensor.vacuum_last_cleaned:
      friendly_name: Senast städat
      icon: mdi:calendar-clock
      device_class: timestamp
    sensor.template_roborock_filter:
      friendly_name: Filter
    sensor.template_roborock_mainbrush:
      friendly_name: Huvudborste
    sensor.template_roborock_sidebrush:
      friendly_name: Sidoborste
    sensor.template_roborock_sensors:
      friendly_name: Sensorer

    #sidebar_information.yaml
    switch.watchtower:
      icon: custom:docker-watchtower
    sensor.databas:
      icon: mdi:database
    sensor.home_assistant_log:
      friendly_name: Loggfil
      icon: mdi:file-document
    sensor.uptime:
      friendly_name: Senast omstart
      icon: mdi:update
      device_class: timestamp
    sensor.docker_cpu:
      friendly_name: Processor
      icon: mdi:chip
    switch.galaxy_tab_a_screensaver:
      friendly_name: Skärmsläckare
      icon: mdi:power-sleep
    light.galaxy_tab_a_screen:
      friendly_name: Display
      icon: mdi:tablet
    binary_sensor.galaxy_tab_a_plugged_in:
      friendly_name: Strömtillförsel
      icon: mdi:power-plug
    sensor.galaxy_tab_a_battery_level:
      friendly_name: Batteri
    sensor.nas_volume_1_average_disk_temp:
      friendly_name: Disktemperatur
    sensor.processor_use_percent:
      icon: mdi:chip

    # vardagsrum_tv.yaml
    automation.tv_on_lights:
      friendly_name: Tänd Tv-lampa

    # studio_dator.yaml
    sensor.template_imac_cpu:
      friendly_name: Processor
      icon: mdi:chip
    sensor.template_imac_mem:
      friendly_name: Minne
      icon: mdi:memory
    automation.macos_notification_motion_hall:
      friendly_name: Mottag notiser
      icon: mdi:bell
    sensor.template_imac_uptime:
      friendly_name: Senaste omstart
      icon: mdi:update
      device_class: timestamp
    sensor.template_imac_system_ssd:
      friendly_name: System SSD
      icon: custom:imac-ssd
    sensor.template_imac_macintosh_hd:
      friendly_name: Macintosh HD
      icon: mdi:harddisk

    # studio_monitorer.yaml
    switch.wemo_monitors:
      friendly_name: Monitorer
      icon: custom:studio-monitor
    automation.turn_off_monitors:
      friendly_name: Stäng av när dator stängs av
      icon: mdi:power
    automation.eq_calibration:
      friendly_name: Automatisk kalibrationsprofil
      icon: custom:eq-calibrate

    # sovrum_flakt.yaml
    automation.sovrum_anslut_turn_on_temp:
      friendly_name: Slå på om 24 °C överskrids
      icon: mdi:chart-bell-curve-cumulative

    #person
    person.matte:
      entity_picture: /local/mattias.png
    person.sanja:
      entity_picture: /local/sanja.png
    device_tracker.mattias_iphone_ios:
      entity_picture: /local/device_tracker.svg

    sensor.mattias_weight:
      unit_of_measurement: kg
